# Generated by Django 5.1.2 on 2024-10-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotaor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(choices=[('Project_Eagle', 'Project Eagle'), ('Project_Original', 'Project Original'), ('Project_Dspace', 'Project Dspace')], max_length=250)),
                ('project_Id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(choices=[('Team_Pioneers', 'UAI Team'), ('Team_Pixel', 'UAI Team'), ('Team_Alpha', 'Magna Team'), ('Team_Phoenix', 'Up2datz')], max_length=250)),
                ('lead_name', models.CharField(default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('2d bb creation', '2D BB Creation'), ('3d bb creation', '3D BB Creation'), ('2d bb check and correct', '2D BB Check and Correct'), ('3dbb/2d bb deletion', '3DBB/2D BB Deletion'), ('2d polyline', '2D Polyline'), ('3d/2d bb dynamic', '3D/2D BB DYNAMIC'), ('3d/2d bb static', '3D/2D BB STATIC')], max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Qualitychecker.project')),
            ],
        ),
        migrations.CreateModel(
            name='Quality_check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('clip_name', models.CharField(max_length=250)),
                ('total_annotation', models.IntegerField()),
                ('objects_checked', models.IntegerField()),
                ('attibutes_error', models.IntegerField()),
                ('geometry_precision_error', models.IntegerField()),
                ('tracking_error', models.IntegerField()),
                ('class_label_error', models.IntegerField()),
                ('missing_error', models.IntegerField()),
                ('unwanted_bbox_error', models.IntegerField()),
                ('comments', models.CharField(max_length=250)),
                ('annotator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_name', to='Qualitychecker.annotaor')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_name', to='Qualitychecker.project')),
                ('qualitycheck_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_name', to=settings.AUTH_USER_MODEL)),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_name', to='Qualitychecker.project_types')),
            ],
        ),
        migrations.CreateModel(
            name='Qualitycheck_Output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attibute_percentage', models.CharField(max_length=50)),
                ('geometry_percentage', models.CharField(max_length=50)),
                ('tracking_percentage', models.CharField(max_length=50)),
                ('class_percentage', models.CharField(max_length=50)),
                ('missing_percentage', models.CharField(max_length=50)),
                ('bbox_percentage', models.CharField(max_length=50)),
                ('annotatorquality_percentage', models.CharField(max_length=50)),
                ('qc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_name', to='Qualitychecker.quality_check')),
            ],
        ),
        migrations.AddField(
            model_name='annotaor',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Annotator', to='Qualitychecker.team'),
        ),
    ]
