# Generated by Django 5.1.2 on 2024-10-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qualitychecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project_types',
            name='task_type',
            field=models.CharField(max_length=250),
        ),
    ]
