# Generated by Django 5.1.2 on 2024-10-18 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qualitychecker', '0002_alter_project_project_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotaor',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualitychecker.team'),
        ),
        migrations.AlterField(
            model_name='project_types',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualitychecker.project'),
        ),
        migrations.AlterField(
            model_name='quality_check',
            name='annotator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualitychecker.annotaor'),
        ),
        migrations.AlterField(
            model_name='quality_check',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualitychecker.project'),
        ),
        migrations.AlterField(
            model_name='quality_check',
            name='qualitycheck_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quality_check',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualitychecker.project_types'),
        ),
        migrations.AlterField(
            model_name='qualitycheck_output',
            name='qc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualitychecker.quality_check'),
        ),
    ]
